fix: check for tmux in tmux utilities
Check for the `tmux` command and an appropriate session in
`tmux-sessionizer` and `project-windowizer`.

Remove support for the Google-specific tmx2 command.

Signed-off-by: Ian Lewis <ian@ianlewis.org>

diff --git a/bin/all/project-windowizer b/bin/all/project-windowizer
--- a/bin/all/project-windowizer
+++ b/bin/all/project-windowizer
@@ -42,6 +42,11 @@ function _main() {
     # Command line parsing is done here.
     argsparse_parse_options "$@"
 
+    if ! command -v tmux >/dev/null 2>&1; then
+        echo "${0}: ERROR: this script requires tmux." >&2
+        exit 1
+    fi
+
     if [[ -z ${TMUX+x} ]]; then
         echo "${0}: ERROR: this script requires tmux to be running." >&2
         exit 1
